import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Common.module.css';
import Footer from './common/Footer';

const Home: React.FC = () => {
  return (
    <div className={styles.content}>
      <Head>
        <title>Akatsuki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Akatsuki</h1>
        <div>ようこそー</div>
        <Link href="Home">Homeへ</Link>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
